name: Data

on:
    push:
        branches: [main]
        paths:
            - "data/*"

    workflow_dispatch: {}

jobs:
    update-readme:
        name: Update README
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Update Data
              run: |
                  chmod +x scripts/update-data.sh
                  ./scripts/update-data.sh

            - name: Commit
              run: |
                  git config --local user.email "actions@github.com"
                  git config --local user.name "GitHub Actions"
                  git add README.md
                  git commit -m "Update README Data"
                  git push
